### PR TITLE
gcc: Add CT_CC_GCC_TM_CLONE_REGISTRY config

### PR DESCRIPTION
**Pull request by stephanosio**
This commit adds a new gcc config `CT_CC_GCC_TM_CLONE_REGISTRY` that
enables the GCC transactional memory clone registry feature for libgcc.

Note that the gcc option to control this feature is only available in
gcc 10 and above.
(see gcc commit 5a4602805eb3ebddbc935b102481e63bffc7c5e6)

Signed-off-by: Stephanos Ioannidis <root@stephanos.io>

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Should send this to upstream crosstool-ng

**Comment by stephanosio** [comment]
Marking DNM for now, as it still needs to be tested.

**Comment by stephanosio** [comment]
Verified working (`.tm_clone_table` section is no longer present in `crtbegin.o`).

**Comment by stephanosio** [comment]
> Should send this to upstream crosstool-ng

Upstream PR is here: https://github.com/crosstool-ng/crosstool-ng/pull/1523

**Comment by stephanosio** [comment]
UPDATE: Added missing gcc package milestones 9 and 10.

**Comment by stephanosio** [comment]
This patch was merged upstream.

**Pull request closed without merging**
